workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.16.2
    scripts:
      - flutter packages get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/**/*.apk

